apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
namespace: dev
images:
  - name: andreasevers/go-sample-app # used for Kustomize matching
    newTag: kpack-0.0.1-b4.20200626.165605
namePrefix: dev-
